const modal=document.getElementById("modal"),content=document.getElementById("content");
const money=n=>Number(n).toFixed(2);
const el=id=>document.getElementById(id);
function tool(type){const views={percentage,change:percentChange,discount,age,loan,interest,tip,bmi,date,convert:converter,text:textCounter};if(!views[type])return;content.innerHTML=views[type]();modal.classList.add("show");const first=content.querySelector("input,select,textarea,button");if(first)first.focus()}
function closeTool(){modal.classList.remove("show")}
modal.addEventListener("click",e=>{if(e.target===modal)closeTool()});
document.addEventListener("keydown",e=>{if(e.key==="Escape")closeTool()});
const inp=(id,label,value,step="any")=>'<label>'+label+'<input id="'+id+'" type="number" step="'+step+'" value="'+value+'"></label>';
function box(title,fields,button,fn,note=""){return '<h2>'+title+'</h2>'+(note?'<p class="note">'+note+'</p>':'')+'<div class="form">'+fields.join("")+'<button type="button" data-action="'+fn+'">'+button+'</button></div><div id="result" class="result"></div>'}
function percentage(){return box("Percentage Calculator",[inp("part","Value",25),inp("whole","Total",200)],"Calculate","calcPercentage")}
function calcPercentage(){const p=Number(el("part").value),w=Number(el("whole").value),r=el("result");if(!Number.isFinite(p)||!Number.isFinite(w)||w===0){r.textContent="Enter a valid value and a non-zero total.";return}const result=p/w*100;if(!Number.isFinite(result)){r.textContent="These values are too large for a reliable percentage.";return}r.innerHTML='<strong>'+result.toFixed(2)+'%</strong>'+p+' is this percentage of '+w+'.'}
function percentChange(){return box("Percentage Change",[inp("oldv","Original value",100),inp("newv","New value",125)],"Calculate","calcChange")}
function calcChange(){const a=Number(el("oldv").value),b=Number(el("newv").value),r=el("result");if(!Number.isFinite(a)||!Number.isFinite(b)||a===0){r.textContent="Original value must not be zero.";return}const change=(b-a)/Math.abs(a)*100;if(!Number.isFinite(change)){r.textContent="These values are too large for a reliable percentage change.";return}r.innerHTML='<strong>'+change.toFixed(2)+'%</strong> change.'}
function discount(){return box("Discount Calculator",[inp("price","Original price",100),inp("disc","Discount (%)",20)],"Calculate","calcDiscount")}
function calcDiscount(){const p=Number(el("price").value),d=Number(el("disc").value),r=el("result");if(!Number.isFinite(p)||p<0||!Number.isFinite(d)||d<0||d>100){r.textContent="Enter a valid price and a discount from 0% to 100%.";return}const finalPrice=p*(1-d/100),saved=p*d/100;if(!Number.isFinite(finalPrice)||!Number.isFinite(saved)){r.textContent="These values are too large for a reliable discount result.";return}r.innerHTML='<strong>'+money(finalPrice)+'</strong>You save '+money(saved)+'. The calculation works with any currency.'}
function age(){return '<h2>Age Calculator</h2><div class="form"><label>Date of birth<input id="dob" type="date"></label><button type="button" data-action="calcAge">Calculate age</button></div><div id="result" class="result"></div>'}
function calcAge(){const value=el("dob").value,r=el("result");if(!value){r.textContent="Enter a date of birth.";return}const d=new Date(value+"T00:00:00"),today=new Date();if(Number.isNaN(d.getTime())||d>today){r.textContent="Enter a valid date of birth that is not in the future.";return}let y=today.getFullYear()-d.getFullYear(),m=today.getMonth()-d.getMonth(),day=today.getDate()-d.getDate();if(day<0){m--;day+=new Date(today.getFullYear(),today.getMonth(),0).getDate()}if(m<0){y--;m+=12}r.innerHTML='<strong>'+y+' years</strong>'+m+' months and '+day+' days.'}
function loan(){return box("Loan Payment Calculator",[inp("p","Loan amount",10000),inp("r","Annual interest (%)",7.5),inp("n","Number of months",60,"1")],"Calculate","calcLoan","Enter any currency amount. No currency conversion is performed.")}
function calcLoan(){const p=Number(el("p").value),rate=Number(el("r").value),months=Number(el("n").value),r=el("result");if(!Number.isFinite(p)||p<=0||!Number.isFinite(rate)||rate<0||!Number.isFinite(months)||months<1||!Number.isInteger(months)){r.textContent="Enter a positive loan amount, a non-negative rate and a whole number of months.";return}const m=rate/1200,payment=m?p*m*Math.pow(1+m,months)/(Math.pow(1+m,months)-1):p/months,total=payment*months;if(!Number.isFinite(payment)||!Number.isFinite(total)){r.textContent="These values are too large for a reliable loan result.";return}r.innerHTML='<strong>'+payment.toFixed(2)+'/month</strong>Total payment: '+total.toFixed(2)+'<br>Total interest: '+(total-p).toFixed(2)}
function interest(){return box("Interest Calculator",[inp("ip","Principal",10000),inp("ir","Annual rate (%)",8),inp("iy","Years",3)],"Calculate","calcInterest")}
function calcInterest(){const p=Number(el("ip").value),rate=Number(el("ir").value),years=Number(el("iy").value),r=el("result");if(!Number.isFinite(p)||!Number.isFinite(rate)||!Number.isFinite(years)||p<0||rate<0||years<0){r.textContent="Enter non-negative values.";return}const simple=p*(rate/100)*years,compound=p*Math.pow(1+rate/100,years)-p;if(!Number.isFinite(simple)||!Number.isFinite(compound)){r.textContent="These values are too large for a reliable interest result.";return}r.innerHTML='<strong>Simple: '+money(simple)+'</strong>Compound: '+money(compound)+' interest.'}
function tip(){return box("Tip & Bill Split",[inp("bill","Bill amount",100),inp("tipRate","Tip (%)",15),inp("people","People",2,"1")],"Calculate","calcTip")}
function calcTip(){const b=Number(el("bill").value),rate=Number(el("tipRate").value),people=Number(el("people").value),r=el("result");if(!Number.isFinite(b)||!Number.isFinite(rate)||!Number.isFinite(people)||b<0||rate<0||people<1||!Number.isInteger(people)){r.textContent="Enter a non-negative bill and tip and a whole number of people.";return}const tipAmount=b*rate/100,total=b+tipAmount,perPerson=total/people;if(!Number.isFinite(tipAmount)||!Number.isFinite(total)||!Number.isFinite(perPerson)){r.textContent="These values are too large for a reliable bill-split result.";return}r.innerHTML='<strong>'+money(perPerson)+' per person</strong>Tip: '+money(tipAmount)+' | Total: '+money(total)}
function bmi(){return box("BMI Calculator",[inp("kg","Weight (kg)",70),inp("cm","Height (cm)",175)],"Calculate","calcBmi","BMI is a screening measure, not a diagnosis.")}
function calcBmi(){const h=Number(el("cm").value)/100,w=Number(el("kg").value),r=el("result");if(!Number.isFinite(h)||!Number.isFinite(w)||h<=0||w<=0){r.textContent="Enter positive height and weight.";return}const bmi=w/(h*h);if(!Number.isFinite(bmi)){r.textContent="These values are too large for a reliable BMI result.";return}r.innerHTML='<strong>'+bmi.toFixed(1)+'</strong>BMI result. Use an appropriate health professional for interpretation.'}
function date(){return '<h2>Date Difference</h2><div class="form"><label>Start date<input id="d1" type="date"></label><label>End date<input id="d2" type="date"></label><button type="button" data-action="calcDate">Calculate</button></div><div id="result" class="result"></div>'}
function calcDate(){const a=el("d1").value,b=el("d2").value,r=el("result");if(!a||!b){r.textContent="Enter both dates.";return}const start=new Date(a+"T00:00:00Z"),end=new Date(b+"T00:00:00Z");if(Number.isNaN(start.getTime())||Number.isNaN(end.getTime())){r.textContent="Enter valid dates.";return}const days=Math.abs((end-start)/86400000);if(!Number.isFinite(days)){r.textContent="These dates are outside the supported range.";return}r.innerHTML='<strong>'+days+' days</strong> between the selected dates.'}
function converter(){return '<h2>Unit Converter</h2><div class="form"><label>Value<input id="uv" type="number" value="1"></label><label>From<select id="uf"><option value="km">Kilometers</option><option value="mi">Miles</option><option value="kg">Kilograms</option><option value="lb">Pounds</option><option value="c">Celsius</option><option value="f">Fahrenheit</option></select></label><label>To<select id="ut"><option value="km">Kilometers</option><option value="mi">Miles</option><option value="kg">Kilograms</option><option value="lb">Pounds</option><option value="c">Celsius</option><option value="f">Fahrenheit</option></select></label><button type="button" data-action="calcConvert">Convert</button></div><div id="result" class="result"></div>'}
function calcConvert(){const v=Number(el("uv").value),a=el("uf").value,b=el("ut").value,r=el("result");let x;if(!Number.isFinite(v)){r.textContent="Enter a valid number.";return}const valid=["km","mi","kg","lb","c","f"];if(!valid.includes(a)||!valid.includes(b)){r.textContent="Those units are not supported.";return}if(a===b)x=v;else if(a==="km"&&b==="mi")x=v*.621371;else if(a==="mi"&&b==="km")x=v/.621371;else if(a==="kg"&&b==="lb")x=v*2.2046226218;else if(a==="lb"&&b==="kg")x=v/2.2046226218;else if(a==="c"&&b==="f")x=v*9/5+32;else if(a==="f"&&b==="c")x=(v-32)*5/9;else{r.textContent="Choose compatible units.";return}if(!Number.isFinite(x)){r.textContent="These values are too large for a reliable conversion result.";return}r.innerHTML='<strong>'+x.toFixed(4).replace(/\.?0+$/,"")+'</strong> '+b.toUpperCase()+' result.'}
function textCounter(){return '<h2>Word & Character Counter</h2><div class="form"><label>Text<textarea id="tc" rows="8" placeholder="Paste or type text here"></textarea></label><button type="button" data-action="calcText">Count</button></div><div id="result" class="result"></div>'}
function calcText(){const s=el("tc").value,words=s.trim()?s.trim().split(/\s+/).length:0;el("result").innerHTML='<strong>'+words+' words</strong>'+s.length+' characters.'}
const search=document.getElementById("search");if(search){search.addEventListener("input",e=>{const q=e.target.value.trim().toLowerCase();document.querySelectorAll("#grid .card[data-search]").forEach(c=>{c.style.display=!q||c.dataset.search.toLowerCase().includes(q)?"flex":"none"})})}


const homeActions=Object.freeze({closeTool,calcPercentage,calcChange,calcDiscount,calcAge,calcLoan,calcInterest,calcTip,calcBmi,calcDate,calcConvert,calcText});
document.addEventListener("click",event=>{const button=event.target.closest("[data-action]");if(!button)return;const action=button.dataset.action;const fn=homeActions[action];if(typeof fn==="function")fn();});
